name: Android Build

on:
  push:
    branches: [ master ]
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11 

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
